// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_Thomas.Models;

#nullable disable

namespace Mission6_Thomas.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20250217014722_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Mission6_Thomas.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            categoryName = "Miscellaneous"
                        },
                        new
                        {
                            categoryId = 2,
                            categoryName = "Drama"
                        },
                        new
                        {
                            categoryId = 3,
                            categoryName = "Television"
                        },
                        new
                        {
                            categoryId = 4,
                            categoryName = "Horror/Suspense"
                        },
                        new
                        {
                            categoryId = 5,
                            categoryName = "Comedy"
                        },
                        new
                        {
                            categoryId = 6,
                            categoryName = "Family"
                        },
                        new
                        {
                            categoryId = 7,
                            categoryName = "Action/Adventure"
                        },
                        new
                        {
                            categoryId = 8,
                            categoryName = "VHS"
                        });
                });

            modelBuilder.Entity("Mission6_Thomas.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("movieCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("movieDirector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("movieName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("movieRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("movieYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
